CREATE TABLE users(
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  username VARCHAR(50)
);
 
CREATE TABLE photos (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  url VARCHAR(200),
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);
 
CREATE TABLE comments (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  contents VARCHAR(240),
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  photo_id INTEGER REFERENCES photos(id) ON DELETE CASCADE
);
 
INSERT INTO users (username) 
VALUES 
  ('Marcus_Webb'),
        ('Sophia.Ramirez'),
        ('TylerJ99'),
        ('Natasha_Bloom'),
        ('Evan.Petrov');
 
INSERT INTO photos (url, user_id)
VALUES
  ('https://shots.marcus.io', 1),
        ('https://gallery.sophia.net', 2),
        ('http://tyler.pics', 3),
        ('https://captures.natasha.com', 4),
        ('http://evan.gallery', 5),
        ('https://imgshare.marcus.ru', 1),
        ('http://photovault.sophia.net', 2),
        ('https://capture.tyler.io', 3),
        ('http://snapzone.natasha.com', 4),
        ('https://pixelframe.evan.net', 5),
        ('http://focuspoint.marcus.io', 1),
        ('https://shutter.sophia.org', 2),
        ('http://lightroom.tyler.biz', 3),
        ('https://exposure.natasha.net', 4),
        ('http://darkroom.evan.com', 5),
        ('https://framing.marcus.info', 1),
        ('http://aperture.sophia.biz', 2),
        ('https://iso.tyler.gallery', 3),
        ('http://lens.natasha.info', 4),
        ('https://depth.evan.com', 5);
 
INSERT INTO comments (contents, user_id, photo_id)
VALUES
  ('Amazing shot, the lighting is absolutely perfect here.', 2, 4),
        ('This photo made my day, truly stunning work.', 5, 5),
        ('Love the composition on this one so much.', 3, 3),
        ('Such vibrant colors captured in this image.', 1, 5),
        ('The background detail here is simply incredible.', 1, 5),
        ('You really captured that moment perfectly.', 1, 3),
        ('This is one of my favorite photos so far.', 1, 2),
        ('The perspective here is really quite unique.', 2, 5),
        ('Gorgeous framing on this particular shot.', 1, 2),
        ('These colors remind me of a summer sunset.', 5, 5),
        ('Simple composition yet so incredibly powerful.', 5, 2),
        ('Your photography skills never cease to amaze me.', 2, 1),
        ('I wish I could take photos half as good as this.', 1, 5),
        ('The focus and depth of field here are spot on.', 1, 4),
        ('Every pixel in this image is pure visual art.', 1, 1),
        ('Wow, this one reminds me of an oil painting.', 5, 3),
        ('Absolutely breathtaking view you captured there.', 1, 1),
        ('The texture in this photo is truly remarkable.', 4, 3),
        ('This image tells such a beautiful story.', 4, 2),
        ('I keep coming back just to look at this photo.', 2, 3),
        ('The way the light falls here is truly magical.', 5, 4),
        ('Such a serene and calming image overall.', 4, 3),
        ('This shot absolutely belongs in a gallery.', 1, 5),
        ('The symmetry here is nothing short of outstanding.', 5, 1),
        ('I love how minimalist and clean this feels.', 5, 1),
        ('You have such a great eye for capturing detail.', 3, 5),
        ('This photo made me smile the moment I saw it.', 4, 5),
        ('The mood conveyed in this photo is incredible.', 4, 5),
        ('I have never seen anything quite like this before.', 4, 5),
        ('How on earth did you get this angle?', 1, 4),
        ('This photo brings back so many wonderful memories.', 2, 5),
        ('The shadows here add so much depth to the image.', 2, 1),
        ('So peaceful and incredibly tranquil to look at.', 1, 3),
        ('The contrast in this image is absolutely perfect.', 5, 4),
        ('Beautiful and deliberate use of negative space.', 3, 1),
        ('This whole scene looks almost completely surreal.', 1, 2),
        ('The color palette chosen for this edit is genius.', 2, 3),
        ('A picture that is truly worth a thousand words.', 3, 1),
        ('Unbelievably good photo, you should be very proud.', 5, 5),
        ('This is exactly the kind of art I deeply admire.', 1, 2),
        ('Such incredible detail visible in every single corner.', 4, 3),
        ('I can feel the whole atmosphere just through this photo.', 4, 4),
        ('This one captures the essence of the scene perfectly.', 4, 1),
        ('What a truly stunning composition this turned out to be.', 2, 5),
        ('The bokeh effect you achieved here is absolutely perfect.', 3, 3),
        ('This photo honestly makes me want to travel there.', 2, 4),
        ('Outstanding and consistent work as always from you.', 5, 1),
        ('The sharpness of detail in this image is impressive.', 4, 3),
        ('A truly timeless photograph that will never get old.', 2, 1),
        ('This looks like it belongs on a magazine cover honestly.', 5, 1),
        ('That fleeting moment was captured so flawlessly here.', 3, 1),
        ('The natural light in this shot is absolutely gorgeous.', 1, 3),
        ('Every time I see this photo I notice something new.', 2, 4),
        ('This is one of those rare photos that speaks to you.', 1, 2),
        ('The simplicity of this shot is its greatest strength.', 2, 2),
        ('The horizon line gives this photograph great balance.', 3, 1),
        ('I truly aspire to take photos as good as this one.', 4, 3),
        ('The grain in this photo actually adds so much character.', 4, 2),
        ('This is raw natural beauty captured perfectly in an image.', 4, 4),
        ('The window light falling here makes everything so warm.', 1, 4),
        ('The tones throughout this shot are so well balanced.', 5, 3),
        ('The editing style on this is absolutely top notch work.', 3, 2),
        ('The rule of thirds is applied so well here, great job.', 2, 2),
        ('This one instantly became one of my all-time favorites.', 1, 4),
        ('The subtle motion blur gives this photo so much life.', 3, 2),
        ('How is this incredible photo not on the explore page?', 1, 4),
        ('The candid and natural feel of this is what I love most.', 5, 3),
        ('Perfectly timed capture, really excellent work done here.', 5, 1),
        ('The wide angle lens choice really works so well here.', 3, 2),
        ('Just look at how those shadows and highlights interact.', 1, 5),
        ('Following for more incredible shots just like this one.', 1, 2),
        ('The leading lines here guide the eye around so perfectly.', 2, 2),
        ('So much raw emotion captured within just one single frame.', 4, 1),
        ('This shot has such a beautiful and dreamlike quality to it.', 2, 3),
        ('The vignette effect you added here creates so much drama.', 4, 2),
        ('Honestly I could sit and stare at this all day long.', 2, 4),
        ('Even the background details in this shot are stunning.', 1, 3),
        ('This feels like it was taken by a seasoned professional.', 4, 4),
        ('The subject placement throughout this frame is spot on.', 1, 3),
        ('Golden hour photography done absolutely right here.', 4, 2),
        ('An image that is just so full of pure wonder and beauty.', 3, 5),
        ('The reflections captured in this shot are so mesmerizing.', 2, 5),
        ('Such a wonderfully unique perspective on an everyday scene.', 3, 5),
        ('The color grading you applied really elevates this shot.', 3, 3),
        ('This composition is honestly nothing short of brilliant.', 4, 5),
        ('The wide depth of field works incredibly well here.', 5, 3),
        ('A picture perfect moment frozen beautifully in time.', 5, 1),
        ('The warmth of the tones here is just so very inviting.', 4, 1),
        ('Such an elegant and carefully refined photograph overall.', 5, 2),
        ('This is definitely my personal favorite from this series.', 5, 1),
        ('The multiple layers in this composition are truly stunning.', 2, 3),
        ('Absolutely flawless execution from the very start to finish.', 4, 3),
        ('The way you use available light is truly inspiring to see.', 3, 3),
        ('I had to share this with absolutely all of my friends.', 3, 4),
        ('The focal point here draws your eye right in immediately.', 4, 2),
        ('This is a perfect example of what great photography looks like.', 3, 3),
        ('An incredible and moving piece of pure visual storytelling.', 5, 4),
        ('The editing style here suits the subject matter perfectly.', 5, 4),
        ('This photo radiates such wonderful energy and movement.', 3, 3);